language: node_js

node_js:
  - "node"

before_install:
  - sudo apt-get install -y libsecret-1-dev

install:
  - npm install -g gulp-cli
  - npm ci || travis_terminate 1

script:
  - gulp build || travis_terminate 1
  - gulp cover || travis_terminate 1
  - node_modules/codecov/bin/codecov -f coverage/coverage-ts.json

addons:
  apt:
    update: true
